services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "gradle test; sleep infinity"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT:-4400}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/os_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
      - test

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: os_test
    volumes:
      - ./docker/config/init.sql:/docker-entrypoint-initdb.d/init.sql
