services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: os-nsu
    volumes:
      - ./docker/config/init.sql:/docker-entrypoint-initdb.d/init.sql